# Clustered FL Strategy Configuration
name: clusteredfl
_target_: src.strategies.clusteredfl.CustomClusteredFL

# ClusteredFL specific parameters (cosine similarity based, per Sattler et al. paper)
cosine_similarity_threshold: 0.7  # min mean cosine similarity to keep cluster together
min_cosine_similarity: 0.3        # min pairwise cosine similarity before considering split
split_warmup_rounds: 5            # rounds to wait before allowing splits
split_cooldown_rounds: 3          # rounds to wait between splits
min_clients_for_split: 3          # minimum clients in cluster to consider split
min_cluster_size: 2               # minimum clients per resulting cluster
max_kmeans_iters: 10              # max iterations for spherical k-means

