# FDMS Strategy Configuration
name: fdms
_target_: src.strategies.fdms.FDMS

# fdms specific parameters
min_common_rounds: 1
fallback_mode: mean  # mean, latest, or uniform
similarity_eps: 1e-12
inplace: true  # used for the internal fedavg aggregator
