# MIFA Strategy Configuration
name: mifa
_target_: src.strategies.mifa.CustomMIFA

# MIFA specific parameters
base_server_lr: 1.0     # server learning rate for aggregation
client_lr: 0.01         # client learning rate (for update normalization)
local_steps: 1          # number of local SGD steps per client
wait_for_all_clients_init: true  # wait for all clients before starting updates

