# MIFA Strategy Configuration
name: mifa
_target_: src.strategies.mifa.CustomMIFA

# MIFA specific parameters
base_server_lr: 0.5     # server learning rate for aggregation (0.5 works well for most cases)
wait_for_all_clients_init: true  # wait for all clients before starting updates

