# CIFAR-100 Dataset Configuration
name: cifar100
_target_: src.datasets.loader.load_data

# dataset identifier for flwr-datasets
dataset_name: uoft-cs/cifar100
num_classes: 100

# keys used in the huggingface dataset
# note: cifar100 uses 'fine_label' for 100 classes, 'coarse_label' for 20 superclasses
image_key: img
label_key: fine_label

# image properties
image_size: 32
channels: 3

# normalization values
normalize:
  mean: [0.5071, 0.4867, 0.4408]
  std: [0.2675, 0.2565, 0.2761]

# data augmentation
augmentation:
  train:
    random_crop: true
    random_horizontal_flip: true
  test:
    random_crop: false
    random_horizontal_flip: false

