# Shakespeare Character-Level Language Modeling Dataset Configuration
name: shakespeare
_target_: src.datasets.nlp_loader.load_text_data

# Dataset identifier for huggingface/flwr-datasets
dataset_name: tiny_shakespeare

# Task type - used to select appropriate client
task_type: char_lm

# Vocabulary and sequence configuration
vocab_size: 79     # Unique characters in Shakespeare corpus
num_classes: 79    # Same as vocab_size (for model output)
sequence_length: 80
stride: 10                      # Skip positions when building sequences (1=all, 10=1/10th)
max_sequences_per_client: 10000  # Cap sequences per client (LEAF uses ~1-5k)

# Keys used in the dataset
text_key: text
label_key: null    # LM uses shifted input as target

# Placeholder values for compatibility with CV-focused code
# (these are not used for NLP but some code paths may reference them)
image_size: 0
channels: 0
