# Transformer Model Configuration for Character-Level Language Modeling
name: char_transformer
_target_: src.models.registry.get_model

# Model architecture parameters
embed_dim: 256
num_heads: 4
num_layers: 4
ff_dim: 512
dropout: 0.1
max_seq_len: 128
