# Dirichlet (Non-IID) Partitioner Configuration - Medium Skew
# alpha = 0.5 creates moderate heterogeneity across clients
name: dirichlet
_target_: flwr_datasets.partitioner.DirichletPartitioner

# medium heterogeneity setting
alpha: 0.5

# partition by label
partition_by: label

# random seed for reproducibility
seed: 42

