# Standard Node Drop Scenario Configuration (scaled for 20 clients)
# Rolling drop: stagger 4 clients dropping and rejoining
name: node_drop_standard_20clients
_target_: src.scenarios.node_drop.NodeDropScenario

enabled: true

# define which clients drop and when
# format: list of {client_ids: [ids], disconnect_round: int, rejoin_round: int}
drop_events:
  - client_ids: [1]
    disconnect_round: 7
    rejoin_round: 31
  - client_ids: [2]
    disconnect_round: 9
    rejoin_round: 31
  - client_ids: [3]
    disconnect_round: 11
    rejoin_round: 31
  - client_ids: [4]
    disconnect_round: 13
    rejoin_round: 31

# alternatively, use automatic mode based on partition id
auto_mode:
  enabled: false
  # clients with partition_id >= start_partition_id will disconnect
  start_partition_id: 2
  # disconnect round = partition_id + offset
  disconnect_offset: 3
  # all clients rejoin at this round
  rejoin_round: 31
